Repository NCAS-CMS/PyActiveStorage, pull requests merged in 2022-10, with the labels that each got.

#16 Keep dependencies versions under control via conda lock file
  .github/workflows/create-condalock-file.yml
  .github/workflows/install-from-condalock-file.yml
  conda-linux-64.lock
Labels: enhancement, testing

#14 clean up module `active_tools.py`
  activestorage/active_tools.py
Labels: standards

#15 starting some docs for our next meeting discussions
  docs4understanding/active.md
  docs4understanding/zarr related/How Zarr to HDF via kerchunk currently works.md
  docs4understanding/zarr related/Logical Process.md
  docs4understanding/zarr related/indexer_for_selection.md
  docs4understanding/zarr related/stack_explained.md
Labels: documentation, excalibur

#17 Suggested modifications for dask integration
  README.md
  activestorage/__init__.py
  activestorage/active.py
  activestorage/netcdf_to_zarr.py
  tests/test_harness.py
Labels: enhancement, Dask

#24 Missing and compression/filtering Issues
  activestorage/active.py
  activestorage/storage.py
Labels: enhancement

#27 Add real world test suite
  activestorage/active.py
  activestorage/dummy_data.py
  activestorage/storage.py
  old_code/test_harness-learning.py
  tests/test_bigger_data.py
  tests/test_data/cesm2_native.nc
  tests/test_data/emac.nc
  tests/test_harness.py
Labels: testing

#29 Diagrams
  doc/figures/hardware-view1.pu
  doc/figures/hardware-view1.svg
  doc/figures/hardware-view2.pu
  doc/figures/hardware-view2.svg
  doc/figures/hardware-view3.pu
  doc/figures/hardware-view3.svg
  doc/figures/software-view1.pu
  doc/figures/software-view1.svg
  doc/figures/update.sh
Labels: documentation
