Repository NCAS-CMS/PyActiveStorage, pull requests merged in 2023-09, with the labels that each got.

#144 update script that starts minio
  tests/s3_exploratory/minio_scripts/minio-start
Labels: bug

#138 Always load netCDF metadata
  activestorage/active.py
  tests/test_bigger_data.py
Labels: bug

#146 Streamline call to `kerchunk.SingleHdf5ToZarr` and add some performance metrics
  .github/workflows/test_s3_minio.yml
  activestorage/netcdf_to_zarr.py
  tests/s3_exploratory/parse_pymon.py
  tests/s3_exploratory/test_s3_arrange_files.py
  tests/s3_exploratory/test_s3_performance.py
Labels: data handling

#42 Add an exception catch when cdata is ndarray but compressor is on
  activestorage/active_tools.py
  tests/unit/test_active_tools.py
Labels: testing
